n_trials: 1000
study_name: sample_study
storage: sqlite:///sample_database.db
direction: minimize
hyperparameters:
    optimizer.lr:
            type: float
            args:
                low: 1e-5
                high: 1e-1
                log: true
    optimizer.weight_decay:
            type: float
            args:
                low: 1e-6
                high: 1e-1
                log: true
    dataset.batch_size:
            type: int
            args:
                low: 100
                high: 10000
pruner:
    _target_: optuna.pruners.MedianPruner
    n_startup_trials: 10
    n_warmup_steps: 100
    interval_steps: 1