# @package _global_
hydra:
    sweeper:
        sampler:
            _target_: optuna.samplers.TPESampler
            n_startup_trials: 10
        _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
        direction: minimize
        n_trials: 50
#        storage: sqlite:///${hydra.sweep.dir}.db
#        study_name: ${hydra.sweep.dir}
        storage: postgresql:///optuna
        study_name: optuna
        params:
            train.lr: interval(-5, 7.5)