_target_: rlms_mlr.models.fnn.FNN
device: ${get_device:cuda}
fnn:
    _target_: torch.nn.Sequential
    _args_:
        - _target_: torch.nn.Conv2d
          in_channels: 1
          out_channels: 32
          kernel_size: 3
          stride: 1
        - _target_: torch.nn.ReLU
        - _target_: torch.nn.Conv2d
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 1
        - _target_: torch.nn.ReLU
        - _target_: torch.nn.MaxPool2d
          kernel_size: 2
        - _target_: torch.nn.Dropout
          p: 0.25
        - _target_: torch.nn.Flatten
          start_dim: 1
        - _target_: torch.nn.Linear
          in_features: 9216
          out_features: 128
        - _target_: torch.nn.ReLU
        - _target_: torch.nn.Dropout
          p: 0.5
        - _target_: torch.nn.Linear
          in_features: 128
          out_features: 10
        - _target_: torch.nn.LogSoftmax
          dim: 1